import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    nav_home: 'Home',
    nav_shop: 'Shop',
    nav_categories: 'Categories',
    nav_cart: 'Cart',
    nav_track: 'Track Order',
    hero_cta: 'Explore Collection',
    hero_badge: 'Premium Selection',
    section_choice: 'Choice',
    section_categories: 'Categories',
    section_cat_desc: 'Browse our collection by your favorite categories',
    section_shop: 'Shop',
    section_collection: 'Our Collection',
    section_recommend: 'Recommendations',
    section_recommend_sub: 'For You',
    section_recommend_desc: 'Curated products you might love',
    section_store: 'Visit Our Store',
    section_store_sub: 'Store Info',
    section_brands: 'Brand Partners',
    section_brands_desc: 'Trusted by premium brands worldwide',
    filter_all: 'All',
    filter_new: 'New Collection',
    filter_best: 'Best Seller',
    filter_featured: 'Featured',
    product_add: 'Add to Cart',
    product_added: 'Added',
    product_out: 'Sold Out',
    product_low: 'Limited Stock',
    cart_empty: 'Your cart is empty',
    cart_go_shop: 'Browse Products',
    checkout_title: 'Checkout',
    checkout_shipping: 'Shipping',
    checkout_review: 'Review',
    checkout_name: 'Name',
    checkout_email: 'Email',
    checkout_phone: 'Phone Number',
    checkout_address: 'Full Address',
    checkout_province: 'Province',
    checkout_city: 'City',
    checkout_district: 'District',
    checkout_postal: 'Postal Code',
    checkout_courier: 'Select Courier',
    checkout_note: 'Order Note',
    checkout_next: 'Continue to Review',
    checkout_back: 'Back',
    checkout_place_order: 'Place Order',
    checkout_total: 'Total',
    checkout_subtotal: 'Subtotal',
    checkout_shipping_fee: 'Shipping Fee',
    checkout_delivery_shipping: 'Delivery',
    checkout_delivery_pickup: 'Pickup at Store',
    checkout_payment_method: 'Payment Method',
    success_title: 'Order Successful',
    success_send_wa: 'Send via WhatsApp',
    success_continue: 'Continue Shopping',
    admin_login: 'Admin Login',
    admin_email: 'Email',
    admin_password: 'Password',
    admin_signin: 'Sign In',
    theme_light: 'Light Mode',
    theme_dark: 'Dark Mode',
    age_title: 'Age Verification',
    age_text: 'This site sells alcoholic beverages and is only accessible to visitors aged 21 and above. By continuing, you confirm that you meet the age requirement.',
    age_yes: 'Yes, I am 21+',
    age_no: 'No, I am not old enough',
    footer_brand: 'Premium Wine & Spirits online store. Every bottle tells a story.',
    footer_contact: 'Contact',
    footer_hours: 'Operating Hours',
    footer_hours_detail: 'Mon-Sat: 10:00-21:00 / Sun: 12:00-18:00',
    tracking_title: 'Track Order',
    tracking_subtitle: 'Enter your order number to check delivery status',
    tracking_placeholder: 'Enter order number (example: HB-20260608-XXXX)',
    tracking_btn: 'Track',
    tracking_searching: 'Searching...',
    tracking_not_found: 'Order number not found. Please check again.',
    tracking_enter: 'Enter your order number above to track delivery status.',
    tracking_order: 'Order',
    tracking_customer: 'Customer',
    tracking_payment: 'Payment',
    tracking_status: 'Status',
    tracking_total: 'Total',
    tracking_shipping_detail: 'Shipping Details',
    tracking_items: 'Order Items',
    tracking_progress: 'Shipping Status',
    // Checkout
    co_delivered: 'Delivery',
    co_pickup: 'Pickup at Store',
    co_cod_pay: 'Pay at Store (COD)',
    co_qris_only: 'Digital payment (shipping requires QRIS)',
    co_est_shipping: 'Est. shipping:',
    co_summary: 'Summary',
    co_scan_pay: 'Scan QR code to pay',
    co_pay_store: 'Pay directly at store',
    co_processing: 'Processing...',
    co_terms: 'By clicking, you agree to Hunter Bottle terms & conditions',
    // Admin
    adm_dashboard: 'Admin Dashboard',
    adm_analytics: 'Analytics',
    adm_orders: 'Orders',
    adm_products: 'Products',
    adm_banners: 'Banners',
    adm_logout: 'Logout',
    adm_admin: 'Admin',
    adm_cashier: 'Cashier',
    adm_total_revenue: 'Total Revenue',
    adm_total_orders: 'Total Orders',
    adm_avg_order: 'Avg Order',
    adm_cancelled: 'Cancelled',
    adm_rev_payment: 'Revenue by Payment',
    adm_top_products: 'Top Products',
    adm_calc_bestseller: 'Calculate Bestseller',
    adm_filter_date: 'Filter by Date',
    adm_from: 'From',
    adm_to: 'To',
    adm_filter: 'Filter',
    adm_search_product: 'Search products...',
    adm_add: 'Add',
    adm_no_products: 'No products yet',
    adm_stock: 'stock',
    adm_manage_banners: 'Manage Banners',
    adm_new_banner: 'New Banner',
    adm_no_banners: 'No banners yet',
    adm_active: 'Active',
    adm_inactive: 'Inactive',
    adm_edit: 'Edit',
    adm_delete: 'Delete',
    adm_edit_banner: 'Edit Banner',
    adm_banner_title: 'Title',
    adm_banner_desc: 'Description / Subtitle',
    adm_banner_link: 'Link URL (optional)',
    adm_banner_sort: 'Sort Order',
    adm_banner_expiry: 'Expiry Date (auto-deactivate)',
    adm_banner_image: 'Banner Image',
    adm_banner_upload: 'Click to upload banner image',
    adm_banner_active_label: 'Active — Banner displayed',
    adm_banner_inactive_label: 'Inactive — Banner hidden',
    adm_saving: 'Saving...',
    adm_update_banner: 'Update Banner',
    adm_save_banner: 'Save Banner',
    adm_cancel: 'Cancel',
    adm_edit_product: 'Edit Product',
    adm_new_product: 'Add New Product',
    adm_product_name: 'Product Name',
    adm_category: 'Category',
    adm_select_category: 'Select Category',
    adm_subcategory: 'Subcategory',
    adm_description: 'Description',
    adm_desc_placeholder: 'Describe the product...',
    adm_price: 'Price (Rp)',
    adm_stock_label: 'Stock',
    adm_abv: 'ABV (%)',
    adm_origin: 'Origin',
    adm_weight: 'Weight (grams)',
    adm_discount: 'Discount (%)',
    adm_discount_expiry: 'Discount Expires (Flash Sale)',
    adm_new_tag_expiry: 'New Tag Expires (auto-remove)',
    adm_product_image: 'Product Image',
    adm_upload_click: 'Click to upload image',
    adm_tag_label: 'Product Tags (check to enable)',
    adm_tag_featured: 'Featured',
    adm_tag_featured_desc: 'Shown in recommendations & banners',
    adm_tag_best: 'Best Seller',
    adm_tag_best_desc: 'Mark as top selling product',
    adm_tag_new: 'New Collection',
    adm_tag_new_desc: 'Shown in newest collection',
    adm_tag_active: 'Active',
    adm_tag_active_desc: 'Product visible in public catalog',
    adm_update_product: 'Update Product',
    adm_save_product: 'Save Product',
    adm_no_orders: 'No orders yet',
    adm_refresh: 'Refresh',
    adm_delivery_pickup: 'Pickup',
    adm_delivery_ship: 'Ship',
    adm_customer: 'Customer',
    adm_phone: 'Phone',
    adm_items: 'Order Items',
    adm_all_checked: 'All items ready',
    adm_check_remaining: 'Check {n} more item(s)',
    adm_order_ready: 'Order Ready',
    adm_verify_title: 'Admin Verification',
    adm_verify_desc: 'Enter admin credentials to manually change order status.',
    adm_verify_email: 'Admin Email',
    adm_verify_password: 'Admin Password',
    adm_verify_btn: 'Verify & Confirm',
    adm_verifying: 'Verifying...',
    // Validation
    val_required: 'Required',
    val_image_size: 'Image max 2MB',
    val_image_type: 'Only JPEG, PNG, or WebP allowed',
    val_title_required: 'Title is required',
    val_name_price: 'Name and price are required',
    val_name_phone: 'Name and phone number are required',
    val_city_address: 'City and address are required for shipping',
    val_save_failed: 'Failed to save. Try again.',
    val_login_failed: 'Invalid email or password',
    val_server_down: 'Cannot connect to server. Make sure backend is running on port 8000.',
    val_order_failed: 'Failed to create order. Please try again.',
    val_payment_failed: 'Payment failed. Please try again.',
    val_popup_closed: 'Payment popup closed. Order remains active.',
    val_confirm_cod: 'Confirm COD payment as PAID?',
    val_confirm_ready: 'Mark this order as READY FOR PICKUP?',
    val_confirm_delete_product: 'Delete this product?',
    val_confirm_delete_banner: 'Delete this banner?',
    val_admin_only: 'Only admin can manually change status',
    val_verify_failed: 'Verification failed. Try again.',
    // QuickView
    qv_available: 'Available',
    qv_remaining: 'Left',
    qv_sold_out: 'Sold Out',
    qv_no_desc: 'No description.',
    qv_add_cart: 'Add to Cart',
    // WhatsApp Widget
    wa_reply_time: 'Usually replies within 1 hour',
    wa_sent: 'Message Sent!',
    wa_opening: 'Opening WhatsApp...',
    wa_help_text: 'How can we help? Send us a message directly on WhatsApp.',
    wa_name_placeholder: 'Your Name',
    wa_msg_placeholder: 'Write a message...',
    wa_send: 'Send via WhatsApp',
    // Brand Logos
    br_partners: 'Brand Partners',
    br_trusted: 'Trusted by premium brands worldwide',
  },
  id: {
    nav_home: 'Beranda',
    nav_shop: 'Belanja',
    nav_categories: 'Kategori',
    nav_cart: 'Keranjang',
    nav_track: 'Lacak Pesanan',
    hero_cta: 'Jelajahi Koleksi',
    hero_badge: 'Pilihan Premium',
    section_choice: 'Pilihan',
    section_categories: 'Kategori',
    section_cat_desc: 'Jelajahi koleksi kami berdasarkan kategori favorit Anda',
    section_shop: 'Belanja',
    section_collection: 'Koleksi Kami',
    section_recommend: 'Rekomendasi',
    section_recommend_sub: 'Untuk Anda',
    section_recommend_desc: 'Produk pilihan yang mungkin Anda sukai',
    section_store: 'Kunjungi Toko Kami',
    section_store_sub: 'Info Toko',
    section_brands: 'Brand Partners',
    section_brands_desc: 'Dipercaya oleh brand premium dunia',
    filter_all: 'Semua',
    filter_new: 'Koleksi Baru',
    filter_best: 'Best Seller',
    filter_featured: 'Featured',
    product_add: 'Tambah ke Keranjang',
    product_added: 'Ditambahkan',
    product_out: 'Habis',
    product_low: 'Stok Terbatas',
    cart_empty: 'Keranjang Anda kosong',
    cart_go_shop: 'Lihat Produk',
    checkout_title: 'Checkout',
    checkout_shipping: 'Pengiriman',
    checkout_review: 'Review',
    checkout_name: 'Nama',
    checkout_email: 'Email',
    checkout_phone: 'No. Telepon',
    checkout_address: 'Alamat Lengkap',
    checkout_province: 'Provinsi',
    checkout_city: 'Kota/Kabupaten',
    checkout_district: 'Kecamatan',
    checkout_postal: 'Kode Pos',
    checkout_courier: 'Pilih Kurir',
    checkout_note: 'Catatan Pesanan',
    checkout_next: 'Lanjut ke Review',
    checkout_back: 'Kembali',
    checkout_place_order: 'Buat Pesanan',
    checkout_total: 'Total',
    checkout_subtotal: 'Subtotal',
    checkout_shipping_fee: 'Ongkos Kirim',
    checkout_delivery_shipping: 'Dikirim',
    checkout_delivery_pickup: 'Ambil di Toko',
    checkout_payment_method: 'Metode Pembayaran',
    success_title: 'Pesanan Berhasil!',
    success_send_wa: 'Kirim via WhatsApp',
    success_continue: 'Lanjut Belanja',
    admin_login: 'Login Admin',
    admin_email: 'Email',
    admin_password: 'Password',
    admin_signin: 'Masuk',
    theme_light: 'Mode Terang',
    theme_dark: 'Mode Gelap',
    age_title: 'Konfirmasi Usia',
    age_text: 'Situs ini menjual minuman beralkohol dan hanya dapat diakses oleh pengunjung berusia 21 tahun ke atas. Dengan melanjutkan, Anda menyatakan telah memenuhi syarat usia.',
    age_yes: 'Ya, Saya Berusia 21+',
    age_no: 'Tidak, Saya Belum Cukup Umur',
    footer_brand: 'Toko online premium Wine & Spirits. Setiap botol menyimpan cerita.',
    footer_contact: 'Kontak',
    footer_hours: 'Jam Operasional',
    footer_hours_detail: 'Sen-Sab: 10:00-21:00 / Min: 12:00-18:00',
    tracking_title: 'Lacak Pesanan',
    tracking_subtitle: 'Masukkan nomor pesanan untuk melihat status pengiriman',
    tracking_placeholder: 'Masukkan nomor pesanan (contoh: HB-20260608-XXXX)',
    tracking_btn: 'Lacak',
    tracking_searching: 'Mencari...',
    tracking_not_found: 'Nomor pesanan tidak ditemukan. Periksa kembali.',
    tracking_enter: 'Masukkan nomor pesanan Anda di atas untuk melacak status pengiriman.',
    tracking_order: 'Pesanan',
    tracking_customer: 'Pelanggan',
    tracking_payment: 'Pembayaran',
    tracking_status: 'Status',
    tracking_total: 'Total',
    tracking_shipping_detail: 'Detail Pengiriman',
    tracking_items: 'Item Pesanan',
    tracking_progress: 'Status Pengiriman',
    // Checkout
    co_delivered: 'Dikirim',
    co_pickup: 'Ambil di Toko',
    co_cod_pay: 'Bayar di Tempat (COD)',
    co_qris_only: 'Pembayaran digital (dikirim wajib QRIS)',
    co_est_shipping: 'Estimasi ongkir:',
    co_summary: 'Ringkasan',
    co_scan_pay: 'Scan QR code untuk membayar',
    co_pay_store: 'Bayar langsung saat ambil di toko',
    co_processing: 'Memproses...',
    co_terms: 'Dengan menekan tombol, Anda menyetujui syarat & ketentuan',
    // Admin
    adm_dashboard: 'Dashboard Admin',
    adm_analytics: 'Analytics',
    adm_orders: 'Pesanan',
    adm_products: 'Produk',
    adm_banners: 'Banner',
    adm_logout: 'Keluar',
    adm_admin: 'Admin',
    adm_cashier: 'Kasir',
    adm_total_revenue: 'Total Revenue',
    adm_total_orders: 'Total Orders',
    adm_avg_order: 'Avg Order',
    adm_cancelled: 'Cancelled',
    adm_rev_payment: 'Revenue by Payment',
    adm_top_products: 'Top Produk',
    adm_calc_bestseller: 'Hitung Bestseller',
    adm_filter_date: 'Filter Tanggal',
    adm_from: 'Dari',
    adm_to: 'Sampai',
    adm_filter: 'Filter',
    adm_search_product: 'Cari produk...',
    adm_add: 'Tambah',
    adm_no_products: 'Belum ada produk',
    adm_stock: 'stok',
    adm_manage_banners: 'Kelola Banner',
    adm_new_banner: 'Banner Baru',
    adm_no_banners: 'Belum ada banner',
    adm_active: 'Active',
    adm_inactive: 'Inactive',
    adm_edit: 'Edit',
    adm_delete: 'Hapus',
    adm_edit_banner: 'Edit Banner',
    adm_banner_title: 'Judul',
    adm_banner_desc: 'Deskripsi / Subtitle',
    adm_banner_link: 'Link URL (opsional)',
    adm_banner_sort: 'Urutan Tampil',
    adm_banner_expiry: 'Tanggal Kedaluwarsa (banner otomatis nonaktif)',
    adm_banner_image: 'Gambar Banner',
    adm_banner_upload: 'Klik untuk upload gambar banner',
    adm_banner_active_label: 'Active — Banner ditampilkan',
    adm_banner_inactive_label: 'Inactive — Banner disembunyikan',
    adm_saving: 'Menyimpan...',
    adm_update_banner: 'Update Banner',
    adm_save_banner: 'Simpan Banner',
    adm_cancel: 'Batal',
    adm_edit_product: 'Edit Produk',
    adm_new_product: 'Tambah Produk Baru',
    adm_product_name: 'Nama Produk',
    adm_category: 'Kategori',
    adm_select_category: 'Pilih Kategori',
    adm_subcategory: 'Subkategori',
    adm_description: 'Deskripsi',
    adm_desc_placeholder: 'Deskripsikan produk...',
    adm_price: 'Harga (Rp)',
    adm_stock_label: 'Stok',
    adm_abv: 'ABV (%)',
    adm_origin: 'Asal (Origin)',
    adm_weight: 'Berat (gram)',
    adm_discount: 'Diskon (%)',
    adm_discount_expiry: 'Diskon Berakhir (Flash Sale)',
    adm_new_tag_expiry: 'Tag New Berakhir (otomatis hilang)',
    adm_product_image: 'Gambar Produk',
    adm_upload_click: 'Klik untuk upload gambar',
    adm_tag_label: 'Tag Produk (centang untuk mengaktifkan)',
    adm_tag_featured: 'Featured',
    adm_tag_featured_desc: 'Tampil di rekomendasi & banner',
    adm_tag_best: 'Best Seller',
    adm_tag_best_desc: 'Tandai sebagai produk terlaris',
    adm_tag_new: 'New Collection',
    adm_tag_new_desc: 'Tampil di koleksi terbaru',
    adm_tag_active: 'Active',
    adm_tag_active_desc: 'Produk muncul di katalog publik',
    adm_update_product: 'Update Produk',
    adm_save_product: 'Simpan Produk',
    adm_no_orders: 'Belum ada pesanan',
    adm_refresh: 'Refresh',
    adm_delivery_pickup: 'Pickup',
    adm_delivery_ship: 'Kirim',
    adm_customer: 'Pelanggan',
    adm_phone: 'Telepon',
    adm_items: 'Item Pesanan',
    adm_all_checked: 'Semua item siap',
    adm_check_remaining: 'Centang {n} item lagi',
    adm_order_ready: 'Pesanan Siap',
    adm_verify_title: 'Verifikasi Admin',
    adm_verify_desc: 'Masukkan kredensial admin untuk mengubah status pesanan secara manual.',
    adm_verify_email: 'Email Admin',
    adm_verify_password: 'Password Admin',
    adm_verify_btn: 'Verifikasi & Konfirmasi',
    adm_verifying: 'Memverifikasi...',
    // Validation
    val_required: 'Wajib diisi',
    val_image_size: 'Gambar maksimal 2MB',
    val_image_type: 'Hanya JPEG, PNG, atau WebP yang diperbolehkan',
    val_title_required: 'Judul wajib diisi',
    val_name_price: 'Nama dan harga wajib diisi',
    val_name_phone: 'Nama dan nomor telepon wajib diisi',
    val_city_address: 'Kota dan alamat wajib diisi untuk pengiriman',
    val_save_failed: 'Gagal menyimpan. Coba lagi.',
    val_login_failed: 'Email atau password salah',
    val_server_down: 'Gagal terhubung ke server. Pastikan backend berjalan di port 8000.',
    val_order_failed: 'Gagal membuat pesanan. Silakan coba lagi.',
    val_payment_failed: 'Pembayaran gagal. Silakan coba lagi.',
    val_popup_closed: 'Popup pembayaran ditutup. Pesanan tetap aktif.',
    val_confirm_cod: 'Konfirmasi pembayaran COD sebagai PAID?',
    val_confirm_ready: 'Tandai pesanan ini sebagai SIAP DIAMBIL?',
    val_confirm_delete_product: 'Hapus produk ini?',
    val_confirm_delete_banner: 'Hapus banner ini?',
    val_admin_only: 'Hanya admin yang bisa mengubah status secara manual',
    val_verify_failed: 'Gagal verifikasi. Coba lagi.',
    // QuickView
    qv_available: 'Tersedia',
    qv_remaining: 'Sisa',
    qv_sold_out: 'Habis',
    qv_no_desc: 'Tidak ada deskripsi.',
    qv_add_cart: 'Tambah ke Keranjang',
    // WhatsApp
    wa_reply_time: 'Biasanya membalas dalam 1 jam',
    wa_sent: 'Pesan Terkirim!',
    wa_opening: 'Membuka WhatsApp...',
    wa_help_text: 'Ada yang bisa kami bantu? Kirim pesan langsung ke WhatsApp kami.',
    wa_name_placeholder: 'Nama Anda',
    wa_msg_placeholder: 'Tulis pesan...',
    wa_send: 'Kirim via WhatsApp',
    // Brand Logos
    br_partners: 'Brand Partners',
    br_trusted: 'Dipercaya oleh brand premium dunia',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('hunter_lang') || 'id');

  const toggleLang = () => {
    const next = lang === 'id' ? 'en' : 'id';
    setLang(next);
    localStorage.setItem('hunter_lang', next);
  };

  const t = (key) => translations[lang]?.[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
